feelings/feelings/urls.py
from django.conf import settings
from django.conf.urls import url, include
from django.contrib import admin

from django.views.generic import TemplateView

from rest_framework_jwt.views import obtain_jwt_token

from thoughts import urls as thought_urls
from users import urls as user_urls
from groups import urls as group_urls

from users import routers as user_routers
from thoughts import routers as thought_routers

from thoughts.viewsets import ConditionsView

api_urlpatterns = [
    url(r'', include(user_routers.router.urls)),
    url(r'', include(thought_routers.router.urls)),
]

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^users/', include(user_urls, namespace='users')),
    url(r'^thoughts/', include(thought_urls, namespace='thoughts')),
    url(r'^groups/', include(group_urls, namespace='groups')),
    url(r'^$', TemplateView.as_view(template_name='index.html'), name='home'),
    url(r'^api/', include(api_urlpatterns)),
    url(r'^api-auth/', include('rest_framework.urls', namespace='rest_framework')),
    url(r'^api-token-auth/', obtain_jwt_token),
    url(r'^api/conditions', ConditionsView.as_view()),
    url(r'^o/', include('oauth2_provider.urls', namespace='oauth2_provider')),
]

if settings.DEBUG:
    import debug_toolbar
    urlpatterns += [
        url(r'^__debug__/', include(debug_toolbar.urls)),
    ]

feelings/users/urls.py
from django.conf.urls import url, include

from . import views

urlpatterns = [
    url(r'^dashboard/$', views.Dashboard.as_view(), name='dashboard'),
    url(r'^logout/$', views.LogoutView.as_view(), name='logout'),
    url(r'^signup/$', views.SignUpView.as_view(), name='signup'),
    url('^', include('django.contrib.auth.urls')),
]

feelings/thoughts/models.py
from django.contrib.auth.models import User
from django.db import models
from django.utils import timezone

CONDITIONS = (
    (0, 'Ecstatic'),
    (5, 'Passionate'),
    (10, 'Happy'),
    (15, 'Optimistic'),
    (20, 'Content'),
    (25, 'Bored'),
    (26, 'Tired'),
    (27, 'Hungry'),
    (30, 'Pessimistic'),
    (35, 'Frustrated'),
    (40, 'Overwhelmed'),
    (45, 'Disappointed'),
    (50, 'Worried'),
    (55, 'Angry'),
    (60, 'Jealous'),
    (65, 'Insecure'),
    (70, 'Guilty'),
    (75, 'Fear'),
    (80, 'Grief'),
    (85, 'Despair'),
    (90, 'Paranoid'),
)


class Thought(models.Model):
    user = models.ForeignKey(User, related_name='thoughts')
    recorded_at = models.DateTimeField(default=timezone.now, editable=False)
    condition = models.IntegerField(choices=CONDITIONS)
    notes = models.TextField(blank=True, default='')

    def __str__(self):
        return '{}: {}'.format(self.recorded_at.strftime('%Y-%m-%d %H:%M:%S'), self.get_condition_display())

    class Meta:
        ordering = ['-recorded_at']

feelings/users/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User


class LogoutForm(forms.Form):
    pass


class SignUpForm(UserCreationForm):

    class Meta:
        model = User
        fields = (
            'username',
            'first_name',
            'last_name',
            'email',
            'password1',
            'password2')

    def __init__(self, *args, **kwargs):
        super(SignUpForm, self).__init__(*args, **kwargs)

        self.fields['email'].required = True
        self.fields['first_name'].required = True
        self.fields['last_name'].required = True

feelings/users/views.py
from django.contrib.auth import logout
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.models import User
from django.core.urlresolvers import reverse, reverse_lazy
from django.http import HttpResponseRedirect
from django.views import generic

from braces.views import SelectRelatedMixin

from . import forms


class Dashboard(
    LoginRequiredMixin,
    SelectRelatedMixin,
    generic.DetailView
):
    model = User
    select_related = ('thoughts',)
    template_name = 'users/dashboard.html'

    def get_object(self, queryset=None):
        return self.request.user


class LogoutView(LoginRequiredMixin, generic.FormView):
    form_class = forms.LogoutForm
    template_name = 'users/logout.html'

    def form_valid(self, form):
        logout(self.request)
        return HttpResponseRedirect(reverse('home'))


class SignUpView(generic.CreateView):
    form_class = forms.SignUpForm
    template_name = 'users/signup.html'
    success_url = reverse_lazy('users:dashboard')

feelings/users/templates/users/dashboard.html
{% extends "layout.html" %}
{% load static from staticfiles %}
{% load render_bundle from webpack_loader %}

{% block title %}Dashboard | {{ block.super }}{% endblock %}

{% block content %}
<div class="container">
    <div id="react-app"></div>

    <div class="row">
        <div class="col-md-6">
            <h3>Companies</h3>
            <div class="list-group">
                {% for company in user.companies.all %}
                    <a href="{% url 'groups:companies:detail' slug=company.slug %}" class="list-group-item">{{ company.name }}</a>
                {% endfor %}
            </div>
        </div>
        <div class="col-md-6">
            <h3>Families</h3>
            <div class="list-group">
                {% for family in user.families.all %}
                    <a href="{% url 'groups:families:detail' slug=family.slug %}" class="list-group-item">{{ family.name }}</a>
                {% endfor %}
            </div>
        </div>
    </div>
</div>
{% endblock %}

{% block css %}
    {% render_bundle 'main' 'css' %}
{% endblock %}

{% block js %}
    <script src="{% static 'js/stretchy.js' %}" data-filter="#id_notes" async></script>
    {% render_bundle 'main' 'js' %}
{% endblock %}

feelings/users/templates/users/logout.html
{% extends "layout.html" %}

{% block title %}Logout | {{ block.super }}{% endblock %}

{% block content %}
<div class="container">
    <div class="row">
        <div class="col-md-6">
            <h3>You sure?</h3>
            <form method="POST">
                {{ form.as_p }}
                {% csrf_token %}
                <input type="submit" value="Logout" class="btn btn-default">
            </form>
        </div>
        <div class="col-md-6">
            <h3>Come back soon!</h3>
            <p>This site works best if you use it often!</p>
        </div>
    </div>
</div>
{% endblock %}

feelings/users/templates/users/signup.html
{% extends "layout.html" %}
{% load bootstrap3 %}

{% block title %}Sign Up | {{ block.super }}{% endblock %}

{% block content %}
<div class="container pt">
    <div class="row">
        <div class="col-md-6">
            <h3>Sign Up</h3>
            <form action="" method="POST">
                {% bootstrap_form form %}
                {% csrf_token %}
                <input type="submit" value="Sign Up" class="btn btn-primary">
            </form>
        </div>
        <div class="col-md-6">
            <h3>Record how you're feeling!</h3>
            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Cumque delectus, doloremque ducimus fugiat reprehenderit rerum voluptatem! Beatae cumque cupiditate exercitationem facere harum labore quam? Officiis pariatur perspiciatis quam qui vero.</p>
        </div>
    </div>
</div>
{% endblock %}